Layr-Labs/eigenpod-proofs-generation

README.md

This PR makes it so that developers may copy/paste the example usage snippets to confirm that the CLI is able to successfully generate proofs.
The *Withdrawal Proof* snippet is not working because of the issue described [here](https://github.com/Layr-Labs/eigenpod-proofs-generation/issues/7#issuecomment-1923297961).

Fix example usage snippets

---

README.md

See previous [PR](https://github.com/Layr-Labs/eigenpod-proofs-generation/pull/47/files) for full context.
For `historical_summary_state.slot` I get this:
historical_summary_state.slot = `SLOTS_PER_HISTORICAL_ROOT` * (withdrawal_slot // `SLOTS_PER_HISTORICAL_ROOT`) + 1. 
8192*(7421951//8192) + 1 = 7413761
With the modification I made, I get this, which matches the example:
historical_summary_state.slot = `SLOTS_PER_HISTORICAL_ROOT` * ((withdrawal_slot // `SLOTS_PER_HISTORICAL_ROOT`) + 1).
8192*(7421951//8192 + 1) = 7421952

[Fix]: Typo in formulae, +1 needs to be inside to compute correct index

---

tx_submitoor/main.go
tx_submitoor/tx_submitter/chain_client.go
tx_submitoor/tx_submitter/submit_withdrawal_credential_proof.go

Changes:
- fix struct tags for env variables
- fix flag parsing for commands
- fix default transactionOpts when not signing with a private key

fixes for withdrawal credential command

---

prove_withdrawal.go
tx_submitoor/tx_submitter/submit_withdrawal_proof.go

It was using the array of header files instead of blocks bodies
+ handle error when the provided validatorId isn't in the withdrawal slot with the relevant error message

submitoor withdrawal proof fix

---

tx_submitoor/main.go

Before `Withdrawal credential proof submitted with calldata: \ufffdQ\ufffdR\0000sdfsdf\0000\0000\0000\0000\0000\0000s4fldsfjsd\0000......`
After `Withdrawal credential proof submitted with calldata: e251ef520000000.......`

Fix calldata encoding in generated withdrawal proof calldata

---

cli/core/beaconClient.go
cli/core/status.go
cli/main.go

- Fix timeout for beacon state download (200s should be more than enough)
- Remove erroneous term from calculating the "after" state of running a checkpoint.

Fix bug in calculating `status` with no checkpoint active

---

cli/core/checkpoint.go
cli/main.go

- Add `--proof checkpoint.json` as an argument to `checkpoint`, which allows the proof to be specified.
- Must also specify `--owner` to interact onchain, otherwise it'll throw an error.
Bypasses the normal flow and submits the proof immediately onchain.
NOTE:
- We don't support this for the other "credential" proof type, since you should just generate from latest beacon state anyways (if you fail to submit a proof, just make another one).

Allow checkpoint proofs to be submitted from file

---

cli/core/checkpoint.go
cli/core/messages.go
cli/core/status.go
cli/core/utils.go
cli/core/validator.go
cli/main.go

**Interface**
- `--batch <batchSize>` modifies the default batch size used. @wadealexc determined 80 for checkpoint, 60 for credentials as the values to use. 
- technically all the code is batched now (but < BATCH_SIZE just produces 1 batch).
**Demo** 
on holesky, submitting 1 batch:

Support Batching in CLI + Consent Messages

---

cli/core/validator.go
eigen_pod_proofs.go

- Use a few of the `Compute()` functions, grouped up, to allow the eigenpodproofs object to pre compute some of the data needed for live proving.
- Expose the `proofs` argument on our proof computation function so that the backend can optimistically cache using this structure.

Support precaching of `eigenpodproofs` intermediates

---

cli/README.md
cli/core/status.go
cli/main.go

* check if new proof submitter is actually a new address
* include proof submitter in status output
* changed `--owner` flag to be `--sender`, because now we support 2 different senders

feat: clarify flag usage and make more consistent

---

cli/README.md
cli/core/onchain/EigenPod.go
cli/core/status.go
cli/main.go

- Posts a transaction allowing users to assign an additional address that can submit checkpoint proofs. You can then use the private key of this account when specifying `--owner` for your EigenPod.
*Testing*
Test Transaction: 0x68c6263c2ccdb451df93b40698aa51f391485b77a91d0764358fcfc67ecc2b54

[CLI] Allow users to update their proof submitter

---

cli/core/utils.go
cli/main.go

…s been created before
* When no checkpoint has been created on a pod before, the checkpoint timestamp is 0, and the LastCheckpointedAt for any verified validators is also 0. This fixes SelectCheckpointableValidators  to account for this edge case.

fix SelectCheckpointableValidators w/ no checkpoint

---

cli/core/status.go
cli/core/utils.go
cli/main.go

Problem: especially when testing, it's helpful to create a bunch of checkpoints in a short period of time. This means we're often running the `checkpoint` command when there's no native ETH to be checkpointed, as beacon chain rewards haven't hit the pod since the last checkpoint performed.
This change adds:
* a more specific error message prompting the user to run again with `--force` if their `checkpoint` failed
* output to the `status` command that detects if `--force` will be needed to successfully start the checkpoint

feat: display whether checkpoint must be forced in status cmd

---

cli/core/validator.go

- Code shouldn't panic, it should just return an error appropriately wrapped.

Remove Panics from `core` proofgen

---

cli/core/checkpoint.go
cli/core/tracing.go

- Add an abstraction for tracing that we can use to performance-analyse the proof generation on the backend (which uses cli/core).
- In the CLI this will continue to no-op.

Configurable Tracing

---

cli/core/validator.go
cli/main.go

- We need this for `healthcheck` -- in order to call verifyStaleBalances, you need to be able to generate a credential proof against a specific validator. The normal command won't work for this because it filters validators based on statuses -- here you need to be able to generate the proof regardless of status.

Support generating a credential proof against a specific validator 

---

cli/core/tracing.go

- `val, ok := .(*ptrtype)` syntax doesn't throw if the cast fails, it just returns ok as false.
- the previous syntax panics on a failed assertion, which occurs on null.
Not sure why none of us have repro'd this issue, but this should fix the problem.

Fix panic()'ing type assertion

---

cli/Makefile
cli/README.md
cli/core/Makefile

- The additional dependencies aren't needed unless you're _contributing_ to the CLI.
- Removed all steps except `go build`, which is needed to build the binary.

Update Build Instructions

---

cli/core/status.go
cli/core/utils.go
cli/main.go

Related to core PR: https://github.com/Layr-Labs/eigenlayer-contracts/pull/668

fix: separate out validators who are awaiting activation queue

---

cli/main.go

- `specificValidator` defaults to `0`, not to max int. 
- Check both cases, just in case.
This whole suite needs to be tested aggressively for issues like this, and to prevent regressions. We will invest in this in the coming week or two.

[bugfix] issue with `credentials` command

---

cli/core/beaconClient.go
cli/core/checkpoint.go
cli/core/utils.go
cli/core/validator.go
cli/flags.go
cli/main.go
cli/utils.go

- If `--print-calldata` is specified during the `credentials` or `checkpoint` command, we will prepare the transaction(s) without sending, and print the calldata as structured JSON.
- For checkpoint proofs, we will print the calldata to start the checkpoint if one is not active yet. if one is already active, we will print the calldata for the proofs, batched according to `--batchSize`.
The proofs will be printed with (TO) and (CALLDATA) fields, all hex encoded. Credential proofs include `validator_indices`, which is an array of validator indices to be attested in that proof. You should submit the sequentially to network, taking care of your nonces as needed. They may be submitted by either the Eigenpod's owner, or an approved proof submitter (see `assign-submitter` command).
We use the …

`--print-calldata` for later proof submission

---

.github/lint.sh
.github/workflows/lint.yml
.golangci.yml
Makefile
beacon/beacon_state_top_level_roots.go
beacon/block.go
beacon/deneb.go
beacon/shared.go
benchmark_test.go
cli/commands/status.go
cli/core/utils.go
cli/flags.go
cli/main.go
common/merkle_utils.go
eigen_pod_proofs.go
prove_validator.go
prove_validator_test.go

- enable `golangci-lint`, which tests for a variety of linter issues.
- right now it's scoped just to `./cli`, but we should enable for the whole repo.

Enable golang linters

---

cli/commands/checkpoint.go
cli/commands/credentials.go
cli/commands/utils.go
cli/core/utils.go
cli/flags.go
cli/main.go

- If you provide `--sender <pk> --gas`, we'll simulate the transaction for you and print out a `gas_estimation` field in the JSON that you can use to understand the costs associated with submitting a transaction. Here are some examples;
- This works for both the `credentials` and `checkpoint` commands :)

Support `--gas` for gas estimation

---

cli/commands/findStalePods.go
cli/commands/staleBalance.go
cli/core/beaconClient.go
cli/core/findStalePods.go
cli/core/status.go
cli/core/utils.go
cli/main.go
go.mod
go.sum

This PR introduces new two commands to the CLI -- `--find-stale-pods` and `--correct-stale-pod`.
`--find-stale-pods`
- This will traverse the beacon state and look for any nodes who have been slashed, s.t their execution balance is now 5% greater than the total sum of their beacon balances. This essentially indicates that you should checkpoint this node again (or, as an external party, invoke `verifyStaleBalances()`).
- This command reports back all the data in JSON by default. If using `--verbose` you can get a non-JSON view with additional log messages.
`--correct-stale-pod`
- Now that you've used the previous command to identify all of the eigenpods who have stale balances, you can use `--corect-stale-pod` to force the pod to start a new checkpoint! The flow looks like this:
- If the …

`--find-stale-pods` and `--correct-stale-pod`

---

cli/commands/checkpoint.go
cli/commands/credentials.go
cli/commands/staleBalance.go
cli/commands/status.go
cli/commands/utils.go
cli/core/findStalePods.go
cli/main.go
cli/utils/utils.go

- When computing the 5% deviation, we should be comparing against the balances of _all_ validators associated with the eigenpod (not just slashed ones).

Update `find-stale-pods` logic

---

cli/core/utils.go

- Removes an explicit check for `chainId==17000` and includes `chainId==0` now for mainnet :)
- We will wait until Friday before upgrade to merge this!

Enable Mainnet on the CLI

---

cli/commands/findStalePods.go
cli/core/findStalePods.go
cli/main.go

`--tolerance 5` indicates that we should tolerate up to (but no more than) a 5% drop in the beacon balance before fixing the execution balance.
- Previously we defaulted to a hardcoded 5 -- this allows folks to set their own version.

`--tolerance` on `find-stale-pods`

---

cli/core/status.go
cli/core/utils.go

1. fix a bug where we pulled the beacon state head even if we have an old checkpoint
2. fix a bug where we compute the wrong diff if the pod owner queues a withdrawal
3. still an outstanding bug: i think `sumRestakedBalancesGwei` also needs to use a prior state if we have an existing checkpoint
see comments below for explanation and testing

feat: fix bugs with status command

---

cli/commands/checkpoint.go
cli/commands/staleBalance.go
cli/core/checkpoint.go

- We missed a few logs during checkpoint proof generation that make parsing output more difficult.
- Remove these logs to fix the command -- they should only show up with --verbose.

Guard logs by verbose

---

cli/core/checkpoint.go
cli/core/status.go
cli/core/utils.go
cli/core/validator.go

-  We were overfetching `GetOnchainValidatorInfo` multiple times in status, due to a regression introduced in [one of our PRs](https://github.com/Layr-Labs/eigenpod-proofs-generation/commit/26f16a4d7be67c68c799700cbba6ae3de0a1e0fc). 
- This PR changes our filtering functions to act on raw data (without fetching / side effects), and pulls our data fetching out into a separate call. This should make `status` about 60~ cheaper to run on average, in terms of network calls.
Before: `./cli status --podAddress 0x2641C2ded63a0C640629F5eDF1189e0f53C06561      9.57s user 9.35s system 4% cpu 7:38.89 total` (458s)
After: `./cli status --podAddress 0x2641C2ded63a0C640629F5eDF1189e0f53C06561      7.24s user 6.09s system 4% cpu 4:52.41 total` (292s)
Overall about a 36% reduction in time for the command.

Make `status` significantly faster

---

cli/core/status.go

master: `./cli status --podAddress 0x2641C2ded63a0C640629F5eDF1189e0f53C06561      6.37s user 7.47s system 4% cpu 5:37.68 total`
now: `./cli status --podAddress 0x2641C2ded63a0C640629F5eDF1189e0f53C06561      5.29s user 5.00s system 6% cpu 2:33.92 total`

Remove a duplicate fetch in `status`

---

cli/core/checkpoint.go
cli/core/multicall/multicall.go
cli/core/status.go
cli/core/utils.go
cli/core/validator.go
go.mod
go.sum

- Support multicall3 (https://www.multicall3.com/) in our status endpoint.
- You can totally see how some of these calls should be codegenned by abigen, which we can iterate on.
Before: `./cli status --podAddress 0x2641C2ded63a0C640629F5eDF1189e0f53C06561      3.60s user 4.62s system 5% cpu 2:38.98 total`
After: `./cli status --podAddress 0x2641C2ded63a0C640629F5eDF1189e0f53C06561      1.71s user 1.00s system 25% cpu 10.646 total`
2:38m -> 10.6s
Tested by running on master/branch for a particular pod and asserting the JSON output. Used a graphical visualizer here so if any keys mismatched, I could figure out which ones. None did.
wooo

Support `multicall3` in status endpoint

---

cli/core/multicall/multicall.go
cli/core/utils.go

- This will allow us to specify the blockNumber/blockHash at which to run the simulation.
- We need this for our indexer and in a few other places.
- Also renamed a few things in the PR.

Support custom `bind.CallOpts` for multicall

---

cli/core/findStalePods.go

- We should've been ignoring balances on validators that are not active.

[bugfix] calculation for finding a stale pod

---

cli/core/findStalePods.go

- Added additional logs under `--verbose` for find-stale-pods.
- Fixed an issue where `allValidatorInfo` (poorly named) was assumed to have validatorInfo structs for _all_ validators, which caused a silent default-value to propagate and under-account for the eigenpod's beacon balance.
- Fixed several floating point precision issues related to uint64 and big.Float.

Fix `find-stale-pods` logic

---

cli/core/findStalePods.go

- This should've been caught with a test, and we will be adding unit tests over most of the pieces of the CLI this year.
- Should be initialized to 0 by default. In the case where all slashed pods had pending withdrawals, this wouldnt have broken, but this is no longer the case.

Fix NPE in `find-stale-pods`
