README.md

Updated the Generate Withdrawal Proof snippet so that it works on copy / paste.
Also updated markdown to include syntax highlighting for bash.

Update Generate Withdrawal Proof snippet 

---

eigen_pod_proofs.go
prove_withdrawal.go

add holesky

---

README.md

Signed-off-by: Kevin Lefevre <lefevre.kevin@gmail.com>

fix: confusing beacon url API path

---

cli/beaconClient.go
cli/checkpoint.go
cli/main.go
cli/utils.go

* also tweaks logging and flag names
* also fixes 2 bugs when filtering validators for a checkpoint

feat: add force flag to checkpoint command

---

cli/Makefile
cli/beaconClient.go
cli/main.go
cli/onchain/EigenPodManager.go
cli/status.go
cli/utils.go

command: `./cli --beacon $NODE_BEACON --eigenpodAddress $EIGENPOD_ADDRESS --node $NODE_ETH --owner $EIGENPOD_PK status`
See your validators, their status, and any pending shares that may be issued if you checkpoint (or complete the active checkpoint). PK isn't required, but the other props are.

`status` command for pepe CLI

---

cli/checkpoint.go
cli/main.go
cli/validator.go

- Move all of the I/O logic out of the generation function, and into `main()`.
- `RunCheckpointProof` and `RunValidatorProof` will now be used directly on the backend.
- (in the next iteration, we'll also provide the beacon state directly to the function, so that the backend can manage its own beacon state downloading as well)

Refactor proof gen for use in backend

---

prove_validator.go

Remove oracleTimestamp

---

cli/Makefile
cli/README.md
cli/core/Makefile

CLI Readme

---

README.md
cli/core/checkpoint.go
cli/core/utils.go
cli/main.go

- Main Readme
- Fix %s on `uint64` printing weird
- Display txns on batch (we failed with no message).
- Force failure if not on Holesky network.
- Add comments re: holesky network support.

Various Updates

---

cli/core/validator.go

- Need this on the backend since we're caching the beacon state periodically.

Expose helper function that doesn't data fetch

---

cli/core/validator.go

- We were printing the wrong number here. Updated to include the correct number!

Fix typo in CLI

---

cli/core/status.go
cli/core/utils.go
cli/main.go

* filters validators into inactive/active/withdrawn
* sorts in order of ascending index

feat: sort output of status command

---

cli/README.md

Clarifying use of eigenpod owner private key

Clarifying use of eigenpod owner private key

---

cli/core/checkpoint.go

- This function will allow us to cache the beacon state on our server, to avoid spurious downloads.
- This API assumes that you've determined the correct beaconState / header to prove against -- for examples of _how_ to do that, see the calling function.

Expose `GenerateCheckpointProofForState` in core lib

---

.github/workflows/cli_release.yml

Fix `goreleaser` builds

---

.github/workflows/cli_release.yml

Fix release process

---

cli/commands/checkpoint.go
cli/commands/credentials.go
cli/commands/findStalePods.go
cli/commands/staleBalance.go
cli/commands/utils.go

Support JSON output in `fix-stale-balance`

---

cli/core/findStalePods.go

- Iteration issue (that I haven't seen previously)
- Some unused code

Fix bug in find-stale-pods

---

cli/core/findStalePods.go

- We were previously ignoring an error that we shouldn't have, which would have indicated I typo'd the mainnet ChainID -- it's 1, not 0.
- Added additional verbose logging for this command, for those who are running locally to better understand what's going on.

Fixed a bug in "find-stale-pods" for mainnet

---

cli/commands/completeAllWithdrawals.go

- Updates for compatibility with holesky testnet

[1.0.1] Update slashing to holesky testnet

---

README.md

chore: update version matrix
